services:
  postgres:
    image: postgres:15.19-trixie
    environment:
      POSTGRES_USER: apikotlin
      POSTGRES_PASSWORD: apikotlin
      POSTGRES_DB: finpes
    ports:
      - "5432:5432"
  api:
    build:
      context: .
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/finpes
      SPRING_DATASOURCE_USERNAME: apikotlin
      SPRING_DATASOURCE_PASSWORD: apikotlin
    ports:
      - "8080:8080"